version: '3'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
    env_file:
      - ./server/.env
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
    env_file:
      - ./client/.env
volumes:
  postgres:
